version: "3.5"
services:
  asterix:
    build: scripts/faker/asterix/.
    ports:
      - "12000:12000"
    environment:
      - VIRTUAL_HOST=asterix
      - VIRTUAL_PORT=12000
#  get_curl:
#    image: appropriate/curl
#    command: ping localhost
  dynamite:
    image: dynamite:latest
    environment:
      - ASTERIX_URL=http://asterix:12000/
#      - ALBUSCLIENT_ALBUS_HOST=http://albusv2:7688
#      - ALBUSCLIENT_NATS_HOSTS=nats://nats-server-1:4222
#      - ALBUSCLIENT_ENABLE_HANDLER_CACHE=true
#      - ALBUSCLIENT_ENABLE_PROPERTY_CACHE=true
#      - ALBUSCLIENT_CONNECTION_TIMEOUT=6000
#      - ALBUSCLIENT_SOCKET_TIMEOUT=12000
#      - ELASTIC_APM_SERVER_URL=http://apm.use.infra:8200
#      - ELASTIC_APM_SERVICE_NAME=qcs-use-1
#      - prometheus_multiproc_dir=/tmp
    links:
      - asterix
    depends_on:
      - asterix
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#volumes:
#  db_data: {}
#  dgraph:
#    external: true