apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: search
  name: dynamite
  labels:
     app: dynamite
#     type: front-end
spec:
  template:
     metadata:
       name: dynamite
       labels:
         app: dynamite
     spec:
         containers:
           - name: dynamite
             image: "marzooqdocker/dynamite:latest"
  replicas: 1
  selector:
    matchLabels:
      app: dynamite
#      type: front-end